# Generated by Django 2.2.16 on 2023-06-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',), 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('name',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Категории',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Заказы',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Продукты',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='Магазины',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Пользователи',
        ),
    ]
