# Generated by Django 4.2.3 on 2023-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230625_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
