# Generated by Django 4.2.3 on 2023-07-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateData',
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='apartment',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Квартира'),
        ),
    ]
