# Generated by Django 4.2.3 on 2023-07-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_updatedata_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='username',
        ),
    ]
